version: 2.1

aliases:
  activate_qemu: &activate_qemu
    run:
      name: Activate QEMU
      command: |
        sudo docker run --rm --privileged multiarch/qemu-user-static:register --reset
  pkg_req: &pkg_req
    requires:
      - dist
      - tar_pkg_tools
  pkg_parameters: &pkg_parameters
    parameters:
      dist:
        description: the Linux distribution (debian|ubuntu|centos)
        type: string
      release:
        description: the release name (stretch|buster|xenial|bionic|7|8)
        type: string
      ext:
        description: the package extension (deb|rpm|apk)
        type: string
      workspace_extra:
        description: extra paths for the workspace root
        type: string
        default: ""
  persist_packages: &persist_packages
    persist_to_workspace:
      root: ~/project/
      paths:
        - "packages"
  store_artifacts: &store_artifacts
    store_artifacts:
      path: ~/project/packages

parameters:
  vc-commit:
    type: string
    default: "HEAD"
  pkg-commit:
    type: string
    default: "master"
jobs:
  tar_pkg_tools:
    description: Builds archives with the packaging tools from https://github.com/varnishcache/pkg-varnish-cache
    docker:
      - image: centos:7
    steps:
      - add_ssh_keys:
          fingerprints:
            - "11:ed:57:75:32:81:9d:d0:a4:5e:af:15:4b:d8:74:27"
      - run:
          name: Grab the pkg repo
          command: |
            yum install -y git
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            echo ${CIRCLE_REPOSITORY_URL}
            git clone https://github.com/varnishcache/pkg-varnish-cache.git .
            git checkout << pipeline.parameters.pkg-commit >>
            tar cvzf debian.tar.gz debian --dereference
            tar cvzf redhat.tar.gz redhat --dereference
            tar cvzf alpine.tar.gz alpine --dereference
            mkdir -p ~/workspace
            mv *.tar.gz ~/workspace
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - debian.tar.gz
            - redhat.tar.gz
            - alpine.tar.gz
      - store_artifacts:
          destination: ~/workspace
          path: ~/workspace
  dist:
    description: Builds varnish-x.y.z.tar.gz that is used later for the package builds
    docker:
      - image: centos:7
    steps:
      - run:
          name: Install deps
          command: |
            yum install -y epel-release
            yum install -y \
                automake \
                jemalloc-devel \
                git \
                libedit-devel \
                libtool \
                libunwind-devel \
                make \
                pcre-devel \
                python3 \
                python-sphinx
      - checkout
      - run:
          name: Create the dist tarball
          command: |
            git checkout << pipeline.parameters.vc-commit >>
            # if version is "trunk", it's a weekly tarball, override the version
            if grep 'AC_INIT.*trunk.*' ./configure.ac; then
                sed -i -e "s/^AC_INIT.*trunk.*/AC_INIT([Varnish], [$(date +%Y%m%d)], [varnish-dev@varnish-cache.org])/" ./configure.ac
                touch .is_weekly
            fi
            ./autogen.des --quiet
            make dist -j 16
            mkdir -p ~/workspace/tools
            mv varnish-*tar.gz ~/workspace/
            if test -e .is_weekly; then mv .is_weekly ~/workspace/; fi
            mv tools/*.suppr ~/workspace/tools/
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .is_weekly
            - varnish*.tar.gz
            - tools/*.suppr
      - store_artifacts:
          destination: ~/workspace
          path: ~/workspace
  x64-rpm:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build AMD64 rpm
          command: |
            cp .circleci/make-rpm-packages.sh .circleci/x64/rpm/
            docker build -t varnish-rpm-package-build:x64 .circleci/x64/rpm/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-rpm-package-build:x64
      - run: find ./ -name "*.rpm"
      - <<: *persist_packages
      - <<: *store_artifacts
  aarch64-rpm:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build aarch64 rpm
          command: |
            cp .circleci/make-rpm-packages.sh .circleci/aarch64/rpm/
            docker build -t varnish-rpm-package-build:aarch64 .circleci/aarch64/rpm/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-rpm-package-build:aarch64
      - run: find ./ -name "*.rpm"
      - <<: *persist_packages
      - <<: *store_artifacts
  x64-deb:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build AMD64 deb
          command: |
            cp .circleci/make-deb-packages.sh .circleci/x64/deb/
            docker build -t varnish-deb-package-build:x64 .circleci/x64/deb/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-deb-package-build:x64
      - run: find ./ -name "*.deb"
      - <<: *persist_packages
      - <<: *store_artifacts

  aarch64-deb:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build aarch64 deb
          command: |
            cp .circleci/make-deb-packages.sh .circleci/aarch64/deb/
            docker build -t varnish-deb-package-build:aarch64 .circleci/aarch64/deb/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-deb-package-build:aarch64
      - run: find ./ -name "*.deb"
      - <<: *persist_packages
      - <<: *store_artifacts

  x64-apk:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build x64 apk
          command: |
            cp .circleci/make-apk-packages.sh .circleci/x64/apk/
            docker build -t varnish-apk-package-build:x64 .circleci/x64/apk/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-apk-package-build:x64
      - run: find ./ -name "*.apk"
      - <<: *persist_packages
      - <<: *store_artifacts

  aarch64-apk:
    <<: *pkg_parameters
    machine: true
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout
      - <<: *activate_qemu
      - run:
          name: Build aarch64 apk
          command: |
            cp .circleci/make-apk-packages.sh .circleci/aarch64/apk/
            docker build -t varnish-apk-package-build:aarch64 .circleci/aarch64/apk/
            docker run --rm -it -e PARAM_DIST=<< parameters.dist >> -e PARAM_RELEASE=<< parameters.release >> -v$(pwd):/varnish-cache -v$HOME/workspace:/workspace varnish-apk-package-build:aarch64
      - run: find ./ -name "*.apk"
      - <<: *persist_packages
      - <<: *store_artifacts
  distcheck:
    parameters:
      dist:
        description: the Linux distribution (debian|ubuntu)
        type: string
      release:
        description: the release name (stretch|buster|xenial|bionic)
        type: string
      extra_conf:
        description: platform-specific configure arguments
        default: ""
        type: string
    docker:
      - image: << parameters.dist >>:<< parameters.release >>
    working_directory: /workspace
    steps:
      - run:
          name: Possibly activate centos:8 extra repos
          command: |
            if [ << parameters.dist >> = centos ]; then
                if [ << parameters.release >> = 8 ]; then
                    dnf install -y 'dnf-command(config-manager)'
                    yum config-manager --set-enabled PowerTools
                    yum install -y diffutils python3-sphinx
                else
                    yum install -y python-sphinx
                fi
                yum install -y epel-release
                yum install -y \
                    automake \
                    jemalloc-devel \
                    libedit-devel \
                    libtool \
                    libunwind-devel \
                    make \
                    pcre-devel \
                    python3 \
                    sudo
            elif [ << parameters.dist >> = debian -o << parameters.dist >> = ubuntu ]; then
                export DEBIAN_FRONTEND=noninteractive
                export DEBCONF_NONINTERACTIVE_SEEN=true
                apt-get update
                apt-get install -y \
                    autoconf \
                    automake \
                    build-essential \
                    ca-certificates \
                    graphviz \
                    libedit-dev \
                    libjemalloc-dev \
                    libncurses-dev \
                    libpcre3-dev \
                    libtool \
                    libunwind-dev \
                    pkg-config \
                    python3-sphinx \
                    sudo
            elif [ << parameters.dist >> = alpine ]; then
                apk update
                apk add -q \
                    autoconf \
                    automake \
                    build-base \
                    ca-certificates \
                    gzip \
                    libedit-dev \
                    libtool \
                    libunwind-dev \
                    linux-headers \
                    pcre-dev \
                    py-docutils \
                    py3-sphinx \
                    tar \
                    sudo
            fi
      - attach_workspace:
          at: /workspace
      - run:
          name: Extract and distcheck
          command: |
            tar xavf *.tar.gz --strip 1
            if [ << parameters.dist >> = centos ]; then
            	adduser varnish
            else
            	adduser --disabled-password --gecos "" varnish
            fi
            chown -R varnish:varnish /workspace

            export ASAN_OPTIONS=abort_on_error=1,detect_odr_violation=1,detect_leaks=1,detect_stack_use_after_return=1,detect_invalid_pointer_pairs=1,handle_segv=0,handle_sigbus=0,use_sigaltstack=0,disable_coredump=0
            export LSAN_OPTIONS=abort_on_error=1,use_sigaltstack=0,suppressions=$(pwd)/tools/lsan.suppr
            export TSAN_OPTIONS=abort_on_error=1,halt_on_error=1,use_sigaltstack=0,suppressions=$(pwd)/tools/tsan.suppr
            export UBSAN_OPTIONS=halt_on_error=1,print_stacktrace=1,use_sigaltstack=0,suppressions=$(pwd)/tools/ubsan.suppr

            sudo -u varnish ./configure \
            	--quiet \
            	--with-unwind \
            	--enable-developer-warnings \
            	--enable-debugging-symbols \
            	--disable-stack-protector \
            	--with-persistent-storage \
            	<< parameters.extra_conf >>
            sudo -u varnish \
            	--preserve-env=ASAN_OPTIONS,LSAN_OPTIONS,TSAN_OPTIONS,UBSAN_OPTIONS \
            	make distcheck VERBOSE=1 -j 12 -k

  collect_packages:
    docker:
      - image: centos:7
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: ls -laR ~/workspace/
      - run:
          name: Tar the packages
          command: |
              tar cvzf packages.tar.gz ~/workspace/packages
      - store_artifacts:
          destination: packages.tar.gz
          path: packages.tar.gz


workflows:
  version: 2
  build:
    jobs:
      - dist
      - tar_pkg_tools
      - aarch64-deb:
          dist: ubuntu
          release: bionic
          ext: deb
          <<: *pkg_req
      - aarch64-rpm:
          dist: centos
          release: "7"
          ext: rpm
          <<: *pkg_req
      - x64-deb:
          dist: ubuntu
          release: bionic
          ext: deb
          <<: *pkg_req
      - x64-rpm:
          dist: centos
          release: "7"
          ext: rpm
          <<: *pkg_req
      - x64-apk:
          dist: alpine
          release: "3"
          ext: apk
          workspace_extra: "/x86_64"
          <<: *pkg_req
#      - aarch64-apk:
#          dist: alpine
#          release: "3"
#          ext: apk
#          workspace_extra: "/aarch64"
#          <<: *pkg_req
      - collect_packages:
          requires:
            - x64-deb
            - x64-rpm
            - x64-apk
#            - aarch64-apk
            - aarch64-deb
            - aarch64-rpm
