name: Coverity Scan

on:
  schedule:
    - cron: 0 8 * * MON
  workflow_dispatch:

jobs:
  coverity:
    if: github.repository_owner == 'varnishcache'
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            autoconf \
            automake \
            build-essential \
            ca-certificates \
            cpio \
            libedit-dev \
            libjemalloc-dev \
            libncurses-dev \
            libpcre2-dev \
            libtool \
            libunwind-dev \
            pkg-config \
            python3-sphinx
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - run: ./autogen.sh
      - run: ./configure --with-persistent-storage
      - uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
        with:
          project: varnish
          email: varnish-dev@varnish-cache.org
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
